// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UIPooc.Data;

#nullable disable

namespace UIPooc.Migrations
{
    [DbContext(typeof(HoldingsDbContext))]
    [Migration("20260328223951_AddedTransactionTypeWatch")]
    partial class AddedTransactionTypeWatch
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UIPooc.Models.Equity", b =>
                {
                    b.Property<int>("EquityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquityId"));

                    b.Property<decimal>("AverageCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Flag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("FlagDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FlagMax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FlagMessage")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("FlagMin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GainLoss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HoldingHigh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("HoldingHighAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("HoldingId")
                        .HasColumnType("int");

                    b.Property<decimal>("HoldingLow")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("HoldingLowAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("IndexWeight")
                        .HasColumnType("decimal(4,2)");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("LastTxnAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("LastTxnPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LastTxnQuantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("LastTxnType")
                        .HasColumnType("int");

                    b.Property<string>("Market")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<decimal>("MarketPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("EquityId");

                    b.HasIndex("HoldingId");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.HasIndex("HoldingId", "Symbol");

                    b.ToTable("Equities");
                });

            modelBuilder.Entity("UIPooc.Models.EquityMarket", b =>
                {
                    b.Property<int>("EquityMarketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquityMarketId"));

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DayHigh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DayLow")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("LastTradeTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("MarketCap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OpenPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PreviousClose")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Week52High")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Week52Low")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("EquityMarketId");

                    b.HasIndex("LastUpdated");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("EquityMarkets");
                });

            modelBuilder.Entity("UIPooc.Models.Holding", b =>
                {
                    b.Property<int>("HoldingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HoldingId"));

                    b.Property<string>("CallName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<bool>("Flag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("FlagDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("FlagMaxIndex")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FlagMessage")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("FlagMinIndex")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Index")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("HoldingId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Holdings");
                });

            modelBuilder.Entity("UIPooc.Models.IndexHistory", b =>
                {
                    b.Property<int>("IndexHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IndexHistoryId"));

                    b.Property<int>("HoldingId")
                        .HasColumnType("int");

                    b.Property<string>("HoldingSnapshot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Index")
                        .HasColumnType("float");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("IndexHistoryId");

                    b.HasIndex("HoldingId");

                    b.HasIndex("RecordedAt");

                    b.HasIndex("HoldingId", "RecordedAt");

                    b.ToTable("IndexHistories");
                });

            modelBuilder.Entity("UIPooc.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<decimal>("Commission")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("HoldingId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TransactionId");

                    b.HasIndex("HoldingId");

                    b.HasIndex("Symbol");

                    b.HasIndex("TransactionDate");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("UIPooc.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UIPooc.Models.Equity", b =>
                {
                    b.HasOne("UIPooc.Models.Holding", "Holding")
                        .WithMany("Equities")
                        .HasForeignKey("HoldingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Holding");
                });

            modelBuilder.Entity("UIPooc.Models.Holding", b =>
                {
                    b.HasOne("UIPooc.Models.User", "User")
                        .WithMany("Holdings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UIPooc.Models.IndexHistory", b =>
                {
                    b.HasOne("UIPooc.Models.Holding", "Holding")
                        .WithMany("IndexHistories")
                        .HasForeignKey("HoldingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Holding");
                });

            modelBuilder.Entity("UIPooc.Models.Transaction", b =>
                {
                    b.HasOne("UIPooc.Models.Holding", "Holding")
                        .WithMany("Transactions")
                        .HasForeignKey("HoldingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UIPooc.Models.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Holding");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UIPooc.Models.Holding", b =>
                {
                    b.Navigation("Equities");

                    b.Navigation("IndexHistories");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("UIPooc.Models.User", b =>
                {
                    b.Navigation("Holdings");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
